### ISSUE TITLE
Adding sound hint for upcoming agitation and metronome-ish sound to guide agitation pattern

### ISSUE THREAD

**Issue by rohitshetty** [hemorej/darkroom-timer#39]
I remember seeing someone using a paid darkroom app and it had nice hints where upcoming agitation was alerted with a sound hint. And then a metronome kind of sound was played to help you invert according to the beat. 

I would like that feature and would like to spend some time contributing if you think it fits with your vision for the web app.

**Comment by hemorej** [comment]
@rohitshetty hm not super interested in adding sound to be honest. Feel free to fork it though
